version: '3.7'
services:
  database:
    image: mariadb:latest
    volumes:
      - "./.docker/mysql:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: wordpress_dev
      MYSQL_PASSWORD: wordpress_dev
      MYSQL_DATABASE: wordpress_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: always
    volumes:
      - "./.docker/data/mysql:/var/lib/mysql:rw"
  wordpress:
    image: wordpress:5.0.0-fpm-alpine
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress_dev
      WORDPRESS_DB_USER: wordpress_dev
      WORDPRESS_DB_PASSWORD: wordpress_dev
      WORDPRESS_VERSION: latest
      WORDPRESS_DEBUG: 1
    volumes:
      - "./.docker/conf/php.ini:/usr/local/etc/php/php.ini"
      - "./.docker/data/wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./themes:/var/www/html/wp-content/themes"
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - "./.docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./.docker/data/wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./themes:/var/www/html/wp-content/themes"
    restart: always
