version: '3.7'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: .
    volumes:
      - ./app:/app
